# Generated by Django 3.2.5 on 2021-07-06 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='prueba',
            name='cantidad',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='prueba',
            name='subtitulo',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
