# Generated by Django 3.2.5 on 2021-08-20 02:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('departamento', '0002_auto_20210819_2149'),
    ]

    operations = [
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=60, verbose_name='Nombres')),
                ('second_name', models.CharField(max_length=60, verbose_name='apellidos')),
                ('job', models.CharField(choices=[('2', 'ECONOMISTA'), ('0', 'CONTADOR'), ('3', 'OTRO'), ('1', 'ADMINISTRADOR')], max_length=1, verbose_name='Trabajo')),
                ('departamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='departamento.departamento')),
            ],
        ),
    ]
