# Generated by Django 3.2.5 on 2021-08-20 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Habilidades',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('habilidades', models.CharField(max_length=50, verbose_name='Habilidades')),
            ],
            options={
                'verbose_name': 'Habilidad',
                'verbose_name_plural': 'Habilidades Empleados',
            },
        ),
        migrations.AlterModelOptions(
            name='empleado',
            options={'ordering': ['first_name', 'second_name'], 'verbose_name': 'Mi empleado', 'verbose_name_plural': 'Los empleados de la empresa'},
        ),
        migrations.AlterField(
            model_name='empleado',
            name='job',
            field=models.CharField(choices=[('3', 'OTRO'), ('1', 'ADMINISTRADOR'), ('0', 'CONTADOR'), ('2', 'ECONOMISTA')], max_length=1, verbose_name='Trabajo'),
        ),
        migrations.AlterUniqueTogether(
            name='empleado',
            unique_together={('first_name', 'second_name')},
        ),
    ]
