# Generated by Django 3.2.5 on 2021-08-23 23:11

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0004_alter_empleado_job'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='hoja_vida',
            field=ckeditor.fields.RichTextField(default='texto'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='empleado',
            name='job',
            field=models.CharField(choices=[('3', 'OTRO'), ('2', 'ECONOMISTA'), ('1', 'ADMINISTRADOR'), ('0', 'CONTADOR')], max_length=1, verbose_name='Trabajo'),
        ),
    ]
