# Generated by Django 3.2.5 on 2021-08-26 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0005_auto_20210823_1811'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='full_name',
            field=models.CharField(blank=True, max_length=120, verbose_name='Nombre completo'),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='job',
            field=models.CharField(choices=[('0', 'CONTADOR'), ('3', 'OTRO'), ('1', 'ADMINISTRADOR'), ('2', 'ECONOMISTA')], max_length=1, verbose_name='Trabajo'),
        ),
    ]
