# Generated by Django 3.2.5 on 2021-09-06 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0006_auto_20210826_1503'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='empleado'),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='job',
            field=models.CharField(choices=[('3', 'OTRO'), ('2', 'ECONOMISTA'), ('0', 'CONTADOR'), ('1', 'ADMINISTRADOR')], max_length=1, verbose_name='Trabajo'),
        ),
    ]
