# Generated by Django 3.2.5 on 2021-09-08 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0007_auto_20210905_2054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleado',
            name='job',
            field=models.CharField(choices=[('0', 'CONTADOR'), ('3', 'OTRO'), ('1', 'ADMINISTRADOR'), ('2', 'ECONOMISTA')], max_length=1, verbose_name='Trabajo'),
        ),
    ]
